; Same as root php.ini
[PHP]
engine = On
extension_dir = "/opt/cpanel/ea-php82/root/usr/lib64/php/modules"
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/mysqlnd.so
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/pdo_mysql.so
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/xml.so
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/dom.so
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/tokenizer.so
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/mbstring.so
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/curl.so
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/fileinfo.so
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/zip.so
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/bcmath.so
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/gd.so
extension = /opt/cpanel/ea-php82/root/usr/lib64/php/modules/intl.so
